[sonic_ssd] Nokia-7215: Fix "show platform ssdhealth"
sonic-net/sonic-platform-common pull request #337
Opened 2022-12-15 15:57 UTC by Pavan-Nokia

Description:
The command is not showing the correct value for ssd health and temperature.

admin@sonic:~$ show platform ssdhealth
Device Model : M.2 (S42) 3IE4
Health       : N/A
Temperature  : N/A

Motivation and Context:
SSD health percentage and temperature not displayed on Nokia-7215 platform.

How Has This Been Tested?
"show platform ssdhealth" cli command on Nokia-7215 and Unittests

Output after fix:
admin@sonic:~$ show platform ssdhealth
Device Model : M.2 (S42) 3IE4
Health       : 100%
Temperature  : 25C

2023-01-20 04:00 UTC, Blueve approved these changes

2023-01-20 04:02 UTC, Blueve commented
@prgeor can you help review this PR?

2023-02-09 21:19 UTC, prgeor requested changes
please wait for my review

2023-03-07 17:30 UTC, prgeor commented
@Pavan-Nokia can you paste the output of `smartctl -a /dev/sda`

2023-03-07 17:36 UTC, prgeor approved these changes

2023-03-07 17:36 UTC, merged

2023-03-07 18:58 UTC, Pavan-Nokia commented
> @Pavan-Nokia can you paste the output of `smartctl -a /dev/sda`

root@sonic:~# smartctl -a /dev/sda
smartctl 7.2 2020-12-30 r5155 [armv7l-linux-5.10.0-18-2-armmp] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF INFORMATION SECTION ===
Device Model:     M.2 (S42) 3IE4
Serial Number:    YCA12206130220275
LU WWN Device Id: 5 24693e 000684700
Firmware Version: L20420i
User Capacity:    16,013,942,784 bytes [16.0 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
TRIM Command:     Available, deterministic, zeroed
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-3 T13/2161-D revision 4
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Wed Mar  1 19:29:02 2023 UTC
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
General SMART Values:
Offline data collection status:  (0x02) Offline data collection activity
                    was completed without error.
                    Auto Offline Data Collection: Disabled.
Total time to complete Offline 
data collection:        (   32) seconds.
Offline data collection
capabilities:            (0x00)     Offline data collection not supported.
SMART capabilities:            (0x0002) Does not save SMART data before
                    entering power-saving mode.
                    Supports SMART auto save timer.
Error logging capability:        (0x00) Error logging NOT supported.
                    General Purpose Logging supported.
SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x0000   000   000   000    Old_age   Offline      -       0
  2 Throughput_Performance  0x0000   000   000   000    Old_age   Offline      -       0
  5 Reallocated_Sector_Ct   0x0012   100   100   001    Old_age   Always       -       0
  7 Unknown_SSD_Attribute   0x0000   000   000   000    Old_age   Offline      -       0
  8 Unknown_SSD_Attribute   0x0000   000   000   000    Old_age   Offline      -       0
  9 Power_On_Hours          0x0012   251   000   000    Old_age   Always       -       2043
 10 Unknown_SSD_Attribute   0x0000   000   000   000    Old_age   Offline      -       0
 12 Power_Cycle_Count       0x0012   015   000   000    Old_age   Always       -       15
163 Unknown_Attribute       0x0000   000   000   000    Old_age   Offline      -       10
168 Unknown_Attribute       0x0000   000   000   000    Old_age   Offline      -       0
169 Unknown_Attribute       0x0000   100   000   000    Old_age   Offline      -       100
175 Program_Fail_Count_Chip 0x0000   000   000   000    Old_age   Offline      -       0
192 Power-Off_Retract_Count 0x0012   002   000   000    Old_age   Always       -       2
194 Temperature_Celsius     0x0002   032   100   000    Old_age   Always       -       32 (3 34 0 30 0)
197 Current_Pending_Sector  0x0000   000   000   000    Old_age   Offline      -       0
225 Unknown_SSD_Attribute   0x0000   000   000   000    Old_age   Offline      -       0
240 Unknown_SSD_Attribute   0x0000   000   000   000    Old_age   Offline      -       0
165 Unknown_Attribute       0x0012   052   000   000    Old_age   Always       -       52
167 Unknown_Attribute       0x0012   025   000   000    Old_age   Always       -       25
170 Unknown_Attribute       0x0013   100   100   001    Pre-fail  Always       -       141
171 Unknown_Attribute       0x0012   000   100   000    Old_age   Always       -       0
172 Unknown_Attribute       0x0012   000   100   000    Old_age   Always       -       0
176 Erase_Fail_Count_Chip   0x0000   000   000   000    Old_age   Offline      -       0
184 End-to-End_Error        0x0012   000   000   000    Old_age   Always       -       0
187 Reported_Uncorrect      0x0012   000   000   000    Old_age   Always       -       0
229 Unknown_Attribute       0x0000   100   100   000    Old_age   Offline      -       89569723955864
232 Available_Reservd_Space 0x0013   000   000   000    Pre-fail  Always       -       0
235 Unknown_Attribute       0x0002   000   000   000    Old_age   Always       -       0
241 Total_LBAs_Written      0x0002   100   100   000    Old_age   Always       -       8662
242 Total_LBAs_Read         0x0002   100   100   000    Old_age   Always       -       7119
SMART Error Log not supported
SMART Self-test Log not supported
Selective Self-tests/Logging not supported
root@sonic:~#