Vsensor common
sonic-net/sonic-platform-common pull request #393
Opened 2023-08-10 01:11 UTC by bmridul

Sonic Platform common changes required as part of Voltage & Current Sensor Monitoring Feature.
#### Description

New base class is introduced for defining voltage and current sensors.
Chassis and Module base classes are enhanced with APIs to retrieve voltage and current sensor data from platform.
#### Motivation and Context

The changes are required to support the design for sensor monitoring feature as proposed in the HLD.

HLD : https://github.com/sonic-net/SONiC/pull/1394
#### How Has This Been Tested?

Tested with CLIs for sensor monitoring.

2023-08-14 02:06 UTC, Junchao-Mellanox requested changes

2023-08-14 02:06 UTC, Junchao-Mellanox commented on sonic_platform_base/module_base.py
> +    def get_num_CurrentSensors(self):
get_num_current_sensors?

2023-08-14 02:06 UTC, Junchao-Mellanox commented on sonic_platform_base/sensor_base.py
> +        Specifies the type of the sensor.
What could be the valid type values?

2023-08-14 02:06 UTC, Junchao-Mellanox commented on sonic_platform_base/sensor_base.py
> +        return SENSOR_TYPE_VOLTAGE
should it be a string instead of integer?

2023-08-14 02:06 UTC, Junchao-Mellanox commented on sonic_platform_base/sensor_base.py
> +        return MILLI_VOLTS
self.MILLI_VOLTS?

2023-08-14 02:06 UTC, Junchao-Mellanox commented on sonic_platform_base/sensor_base.py
> +        return MILLI_AMPS
self.MILLI_AMPS?

2023-08-24 02:36 UTC, Junchao-Mellanox approved these changes

2023-09-07 22:24 UTC, abdosi approved these changes

2023-09-07 22:25 UTC, merged

2023-09-07 22:26 UTC, abdosi commented
@gechiang this is enhancement so will need to go to msft repo. not sure if we can take into 202205 branch.

2023-09-07 22:52 UTC, gechiang commented
> @gechiang this is enhancement so will need to go to msft repo. not sure if we can take into 202205 branch.

Unfortunately we currently do not have a separate MSFT Repo for sonic-platform-common so there is no way to take it in that way... either it is taken up in public 202205 or someone has to create the new MSFT repo for this submodule and also work with build team to enable auto sync works which was not that easy when we did it for sonic-utilities.msft  So unless it is absolutely needed, no plan to create a new msft repo for new features.

2023-09-21 12:25 UTC, StormLiangMS commented
new feature, no cherry pick.